version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: omar
      MONGO_INITDB_ROOT_PASSWORD: omar123
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    ports:
      - "3000:3000"
    environment:
      DB_URI: "mongodb+srv://OmarDB:omar123@mycluster.wkgse.mongodb.net/OmarDB?retryWrites=true&w=majority&appName=MyCluster"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
